import { browser, signIn, flash, base } from "./lib.mjs";
const b = await browser();
const admin = await signIn(b, "admin@kinconnect.local", "kinconnect-admin-1");
const ava = await signIn(b, "ava@kinconnect.local", "family-pass-1");
const uncle = await signIn(b, "uncle@kinconnect.local", "family-pass-1");
console.log("admin home prompt:", await admin.locator("main a:has-text('covers your home base')").allInnerTexts());
await admin.goto(base + "/weather"); console.log("weather alerts:", await admin.locator("section:has-text('Your home base') li").allInnerTexts());
await ava.goto(base + "/weather"); console.log("ava (no location):", await ava.locator("section:has-text('Your home base') p").first().innerText());
await admin.click("button[value=power_out]"); await admin.waitForURL(/alerts\/.+/); console.log("checkin:", await flash(admin));
const checkinUrl = admin.url().split("?")[0];
await ava.goto(base + "/"); console.log("ava pinned:", await ava.locator("main a.border-2").allInnerTexts());
await admin.goto(checkinUrl); await admin.click("button[value=safe]"); await admin.waitForLoadState("networkidle");
await ava.goto(base + "/"); console.log("ava pinned after safe:", await ava.locator("main a.border-2").allInnerTexts());
await admin.goto(base + "/weather"); console.log("prompt gone:", await admin.locator("form:has(button[value=hurt])").count() === 0);
await ava.goto(base + "/vault"); await ava.setInputFiles("#file", "e2e/drill.jpg"); await ava.fill("#title", "Insurance card"); await ava.click("text=Upload privately"); await ava.waitForSelector('text=Uploaded.');
console.log("vault:", await flash(ava));
const openHref = await ava.locator("a:has-text('Insurance card')").first().getAttribute("href");
const own = await ava.request.get(base + openHref, { maxRedirects: 0 }); console.log("owner open:", own.status(), (own.headers().location || "").includes("token="));
console.log("admin before share:", (await admin.request.get(base + openHref, { maxRedirects: 0 })).status());
await ava.selectOption("select[name=target]", { label: "Logan" }); await ava.click("button:has-text('Share')"); await ava.waitForSelector('text=Shared.');
const after = await admin.request.get(base + openHref, { maxRedirects: 0 }); console.log("admin after share:", after.status());
const img = await admin.request.get(after.headers().location); console.log("signed fetch:", img.status(), img.headers()["content-type"]);
await admin.goto(base + "/vault"); console.log("admin shared list:", await admin.locator("section:has-text('Shared with me') li").allInnerTexts());
console.log("uncle:", (await uncle.request.get(base + openHref, { maxRedirects: 0 })).status());
await ava.goto(base + "/vault"); await ava.click("button[aria-label='Remove access']"); await ava.waitForSelector('text=Access removed.');
console.log("admin after revoke:", (await admin.request.get(base + openHref, { maxRedirects: 0 })).status());
await ava.screenshot({ path: "e2e/out/vault.png", fullPage: true });
await b.close();
